apiVersion: apps/v1
kind: Deployment
metadata:
  name: tatamo-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tatamo-pgadmin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: tatamo-pgadmin
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tatamo-pgadmin
        image: tatamo.azurecr.io/pgadmin:latest
        ports:
        - containerPort: 80
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: haninfinity530@gmail.com
          - name: PGADMIN_DEFAULT_PASSWORD
            value: admin
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: tatamo-pgadmin
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tatamo-pgadmin